version: '2.0'
services: 
    web:
        image: nginx:1.13.0-alpine
        container_name: test-nginx
        restart: always
        ports: 
        - "9000:80"
        volumes: 
        - ./html:/usr/share/nginx/html